# Generated by Django 4.0.3 on 2022-09-04 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
